artifact_uri: file://C:/Users/enric/Desktop/Final_results/NIRS_klop/1/bb561736c92546cb8c46a744d5a7ae1c/artifacts
end_time: 1655218408323
entry_point_name: ''
experiment_id: '1'
lifecycle_stage: active
name: ''
run_id: bb561736c92546cb8c46a744d5a7ae1c
run_uuid: bb561736c92546cb8c46a744d5a7ae1c
source_name: ''
source_type: 4
source_version: ''
start_time: 1655218333400
status: 3
tags: []
user_id: eschmitz
