artifact_uri: file://C:/Users/enric/Desktop/Final_results/NIRS_klop/1/4db3ed12cc1d4aad817544b657afb501/artifacts
end_time: 1655218537741
entry_point_name: ''
experiment_id: '1'
lifecycle_stage: active
name: ''
run_id: 4db3ed12cc1d4aad817544b657afb501
run_uuid: 4db3ed12cc1d4aad817544b657afb501
source_name: ''
source_type: 4
source_version: ''
start_time: 1655218408469
status: 3
tags: []
user_id: eschmitz
