artifact_uri: file://C:/Users/enric/Desktop/Final_results/NIRS_klop/2/e830999dc0eb462eaac58ccd3b41d26a/artifacts
end_time: 1655233368890
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
name: ''
run_id: e830999dc0eb462eaac58ccd3b41d26a
run_uuid: e830999dc0eb462eaac58ccd3b41d26a
source_name: ''
source_type: 4
source_version: ''
start_time: 1655233308669
status: 3
tags: []
user_id: eschmitz
