artifact_uri: file://C:/Users/enric/Desktop/Final_results/NIRS_klop/2/1c1744ece5864f229b17b3abf6ec5c60/artifacts
end_time: 1655233393065
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
name: ''
run_id: 1c1744ece5864f229b17b3abf6ec5c60
run_uuid: 1c1744ece5864f229b17b3abf6ec5c60
source_name: ''
source_type: 4
source_version: ''
start_time: 1655233369007
status: 3
tags: []
user_id: eschmitz
