artifact_uri: file://C:/Users/enric/Desktop/Final_results/NIRS_klop/1/07dc24fdca034705abfb4a55c9a34ba7/artifacts
end_time: 1655218388747
entry_point_name: ''
experiment_id: '1'
lifecycle_stage: active
name: ''
run_id: 07dc24fdca034705abfb4a55c9a34ba7
run_uuid: 07dc24fdca034705abfb4a55c9a34ba7
source_name: ''
source_type: 4
source_version: ''
start_time: 1655218346600
status: 3
tags: []
user_id: eschmitz
