artifact_uri: file://C:/Users/enric/Desktop/Final_results/NIRS_klop/1/08fdce4ca75147e9a6b1c30d0a234376/artifacts
end_time: 1655217928203
entry_point_name: ''
experiment_id: '1'
lifecycle_stage: active
name: ''
run_id: 08fdce4ca75147e9a6b1c30d0a234376
run_uuid: 08fdce4ca75147e9a6b1c30d0a234376
source_name: ''
source_type: 4
source_version: ''
start_time: 1655217888406
status: 3
tags: []
user_id: eschmitz
