artifact_uri: file://C:/Users/enric/Desktop/Final_results/NIRS_klop/1/4ea6ce8d6e4544419ed5d1a364ca6907/artifacts
end_time: 1655218529713
entry_point_name: ''
experiment_id: '1'
lifecycle_stage: active
name: ''
run_id: 4ea6ce8d6e4544419ed5d1a364ca6907
run_uuid: 4ea6ce8d6e4544419ed5d1a364ca6907
source_name: ''
source_type: 4
source_version: ''
start_time: 1655218388859
status: 3
tags: []
user_id: eschmitz
