artifact_uri: file://C:/Users/enric/Desktop/Final_results/NIRS_klop/1/4583c4ebced4438cae63da3ce3fd16b7/artifacts
end_time: 1655217759284
entry_point_name: ''
experiment_id: '1'
lifecycle_stage: active
name: ''
run_id: 4583c4ebced4438cae63da3ce3fd16b7
run_uuid: 4583c4ebced4438cae63da3ce3fd16b7
source_name: ''
source_type: 4
source_version: ''
start_time: 1655217635793
status: 3
tags: []
user_id: eschmitz
